### ISSUE TITLE
Latest release failed?

### ISSUE THREAD

**Issue by engeir** [MR-Addict/mdbook-embedify#2]
I notice that the [latest release](https://github.com/MR-Addict/mdbook-embedify/releases) is v0.2.9, while the commits a5c5898d23b05b526b8217ff3be9916cf97e654a and 23eb4e3ede03f9e8da1f050ce2e21350480bcdee both come after this, supposedly released as v0.2.30 in 3bc1ca8ab76361846d0b3ddc18e1e0247578beb6.

**Comment by MR-Addict** [comment]
Thank you for bringing this. I forget to give it a tag and the version number should be 0.2.10.

I just put a new commit, new release should be coming.
